version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run: cat README.md
      - run: which gcloud
      - run: cat $HOME/env/.env

# workflows:
#     version: 2
#     test_and_deploy:
#         jobs:
#             - product:
#                 context: GCR
#                 filters:
#                     branches:
#                         only: master