version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run: cat ./README.md
      - run: which gcloud
      - run: ls -la 
      - run: cat ./env/.env
      - run: echo $testenv
      - run: gcloud compute instance-groups managed list --zones us-east1-b --quiet

# workflows:
#     version: 2
#     test_and_deploy:
#         jobs:
#             - product:
#                 context: GCR
#                 filters:
#                     branches:
#                         only: master